name: Rust

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
            - os: windows-latest
              artifact_name: chuck-norust.exe
              asset_name: chuck-norust.exe

    steps:
    - uses: actions/checkout@v2

    - run: cargo build --release --verbose

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
#    - name: Run tests
#      run: cargo test --verbose
